README.md

Adding hyperlinks in README to Maven and Eclipse.

Minor tweaks in README. 

---

examples/src/main/java/com/hedera/sdk/examples/advanced/MultiAppTransfer.java
examples/src/main/java/com/hedera/sdk/examples/advanced/TransferCryptoToExchange.java
src/main/java/com/hedera/sdk/Client.java

(transferring crypto to an exchange)

implement multiparty signatures example

---

src/main/java/com/hedera/hashgraph/sdk/crypto/Key.java
src/test/groovy/com/hedera/hashgraph/sdk/crypto/ed25519/Ed25519PublicKeyTest.groovy

Key.fromString() should attempt to decode raw bytes if they're the right length

---

src/main/java/com/hedera/hashgraph/sdk/CheckedFunction.java
src/main/java/com/hedera/hashgraph/sdk/Client.java
src/main/java/com/hedera/hashgraph/sdk/HederaCall.java
src/main/java/com/hedera/hashgraph/sdk/HederaException.java
src/main/java/com/hedera/hashgraph/sdk/HederaNetworkException.java
src/main/java/com/hedera/hashgraph/sdk/HederaThrowable.java
src/main/java/com/hedera/hashgraph/sdk/Transaction.java
src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java

document possible throwable types in API

---

src/main/java/com/hedera/hashgraph/sdk/Transaction.java

Transaction: add getter for transaction ID

---

src/main/java/com/hedera/hashgraph/sdk/GetByKeyQuery.java
src/main/java/com/hedera/hashgraph/sdk/GetBySolidityIdQuery.java
src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
src/main/java/com/hedera/hashgraph/sdk/TransactionReceiptQuery.java
src/main/java/com/hedera/hashgraph/sdk/TransactionRecordQuery.java
src/main/java/com/hedera/hashgraph/sdk/account/AccountBalanceQuery.java
src/main/java/com/hedera/hashgraph/sdk/account/AccountClaimQuery.java
src/main/java/com/hedera/hashgraph/sdk/account/AccountInfoQuery.java
src/main/java/com/hedera/hashgraph/sdk/account/AccountRecordsQuery.java
src/main/java/com/hedera/hashgraph/sdk/account/AccountStakersQuery.java
src/main/java/com/hedera/hashgraph/sdk/contract/ContractBytecodeQuery.java
src/main/java/com/hedera/hashgraph/sdk/contract/ContractCallQuery.java
src/main/java/com/hedera/hashgraph/sdk/contract/ContractInfoQuery.java
src/main/java/com/hedera/hashgraph/sdk/contract/ContractRecordsQuery.java
src/main/java/com/hedera/hashgraph/sdk/file/FileContentsQuery.java
src/main/java/com/hedera/hashgraph/sdk/file/FileInfoQuery.java

fix `QueryBuilder.setPayment()` not being fluent

---

pom.xml

Enables compilation of a shaded jar for the SDK.

Addition of "shade" profile

---

src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java

get transaction ID from `bodyBuilder`

---

src/main/java/com/hedera/hashgraph/sdk/account/AccountUpdateTransaction.java

AccountUpdateTransaction: don't require setKey()

---

examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/GetFileContents.java

Get file contents example

---

src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java

Cache the picked node for a query so its inner generated payment is to the same node

---

src/main/java/com/hedera/hashgraph/sdk/CallParams.java
src/test/java/com/hedera/hashgraph/sdk/CallParamsTest.java

supercedes #149 
@gregscullard

CallParams: don't calculate a selector for constructors

---

src/main/java/com/hedera/hashgraph/sdk/Client.java
src/main/java/com/hedera/hashgraph/sdk/Transaction.java
src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java

closes #152 
supercedes #143 
@gregscullard

implement exponential backoff for transaction receipt queries

---

src/main/java/com/hedera/hashgraph/sdk/Transaction.java

fix bug in exponential backoff

---

src/main/java/com/hedera/hashgraph/sdk/CallParams.java
src/main/java/com/hedera/hashgraph/sdk/SolidityUtil.java
src/main/java/com/hedera/hashgraph/sdk/account/AccountId.java
src/main/java/com/hedera/hashgraph/sdk/contract/ContractId.java
src/main/java/com/hedera/hashgraph/sdk/file/FileId.java
src/test/java/com/hedera/hashgraph/sdk/file/SolidityUtilTest.java

closes #155 
cc @gregscullard @mehcode @rahul-ki

implement Solidity address conversions for address/contract/file IDs

---

examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/AddClaim.java

Adds an `AddClaim` to the advanced examples.

add claim example

---

src/main/java/com/hedera/hashgraph/sdk/HederaCall.java

fix `HederaCall.require(String, String)`

---

examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/GetAddressBook.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/LoadAddressBook.java

This is useful for people who need the network address book to inspect public keys, among other things.

create GetAddressBook example

---

examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/CreateAccount.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/CreateFile.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/CreateStatefulContract.java

add transaction fees to examples

---

src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java
src/main/java/com/hedera/hashgraph/sdk/file/FileUpdateTransaction.java
src/test/java/com/hedera/hashgraph/sdk/file/FileUpdateTransactionTest.java

FileUpdateTransaction: don't require .addKey()

---

src/main/java/com/hedera/hashgraph/sdk/Client.java
src/main/java/com/hedera/hashgraph/sdk/Node.java

expose explicit shutdown of channels to silence orphan channel error

---

src/main/java/com/hedera/hashgraph/sdk/file/FileCreateTransaction.java
src/test/java/com/hedera/hashgraph/sdk/file/FileCreateTransactionTest.java

`FileCreateTransaction`: fix validation

---

.travis.yml
pom.xml

this is necessary to actually build on JDK 8

move errorprone plugin config to its own profile

---

pom.xml

enforce that deployment uses JDK 1.8

---

src/main/java/com/hedera/hashgraph/sdk/Client.java

set default max query payment to 1 hbar

---

examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/TransferCrypto.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/UpdateAccountPublicKey.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/simple/CreateAccount.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/simple/TransferCrypto.java
src/main/java/com/hedera/hashgraph/sdk/Client.java
src/main/java/com/hedera/hashgraph/sdk/Transaction.java
src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java

Deprecate `executeForReceipt()` and friends for removal

---

examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/GetAddressBook.java
src/main/java/com/hedera/hashgraph/sdk/file/FileId.java

@mehcode should I add examples for downloading these files as well? (`NodeAddressBook` is already covered)

add useful constants to FileId

---

examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/CreateAccount.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/CreateAccountThresholdKey.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/CreateStatefulContract.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/GetAddressBook.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/GetFileContents.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/MultiAppTransfer.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/TransferCrypto.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/UpdateAccountPublicKey.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/simple/CreateAccount.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/simple/TransferCrypto.java
src/main/java/com/hedera/hashgraph/sdk/Client.java
src/main/java/com/hedera/hashgraph/sdk/Hbar.java
src/main/java/com/hedera/hashgraph/sdk/HbarUnit.java
src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java
src/main/java/com/hedera/hashgraph/sdk/account/AccountCreateTransaction.java
src/main/java/com/hedera/hashgraph/sdk/account/AccountUpdateTransaction.java
src/main/java/com/hedera/hashgraph/sdk/account/CryptoTransferTransaction.java
src/main/java/com/hedera/hashgraph/sdk/contract/ContractCreateTransaction.java
src/main/java/com/hedera/hashgraph/sdk/contract/ContractExecuteTransaction.java
src/test/java/com/hedera/hashgraph/sdk/HbarTest.java

also renamed `ContractExecuteTransaction.setAmount()` to `.setPayableAmount()`

implement Hbar helper class and overload tinybar-accepting APIs for it

---

src/main/java/com/hedera/hashgraph/sdk/CallParams.java
src/main/java/com/hedera/hashgraph/sdk/DurationHelper.java
src/main/java/com/hedera/hashgraph/sdk/GetBySolidityIdQuery.java
src/main/java/com/hedera/hashgraph/sdk/HederaCall.java
src/main/java/com/hedera/hashgraph/sdk/IdUtil.java
src/main/java/com/hedera/hashgraph/sdk/Internal.java
src/main/java/com/hedera/hashgraph/sdk/SolidityUtil.java
src/main/java/com/hedera/hashgraph/sdk/TimestampHelper.java
src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java
src/main/java/com/hedera/hashgraph/sdk/TransactionId.java
src/main/java/com/hedera/hashgraph/sdk/account/AccountId.java
src/main/java/com/hedera/hashgraph/sdk/account/AccountInfo.java
src/main/java/com/hedera/hashgraph/sdk/account/Claim.java
src/main/java/com/hedera/hashgraph/sdk/contract/ContractFunctionResult.java
src/main/java/com/hedera/hashgraph/sdk/contract/ContractId.java
src/main/java/com/hedera/hashgraph/sdk/contract/ContractInfo.java
src/main/java/com/hedera/hashgraph/sdk/crypto/PublicKey.java
src/main/java/com/hedera/hashgraph/sdk/crypto/ed25519/Ed25519Signature.java
src/main/java/com/hedera/hashgraph/sdk/file/FileId.java
src/main/java/com/hedera/hashgraph/sdk/file/FileInfo.java

mark more APIs `@Internal` or `@Deprecated`

---

src/main/java/com/hedera/hashgraph/sdk/account/AccountInfoQuery.java
src/main/java/com/hedera/hashgraph/sdk/contract/ContractInfoQuery.java
src/main/java/com/hedera/hashgraph/sdk/file/FileInfoQuery.java

these should use `Math.max()` not `Math.min()`

fix overrides of `[Account,ContractFile]InfoQuery.getCost()`

---

src/main/java/com/hedera/hashgraph/sdk/contract/ContractFunctionParams.java
src/test/java/com/hedera/hashgraph/sdk/contract/ContractFunctionParamsTest.java

Fix `ContractFunctionParams.addAddress()`

---

src/main/java/com/hedera/hashgraph/sdk/Transaction.java

fix `Transaction.executeAsync()` to auto-sign the transaction

---

src/main/java/com/hedera/hashgraph/sdk/file/FileId.java

FileId: deprecate `[to,from]SolidityAddress`

---

src/main/proto/ConsensusSubmitMessage.proto

Update max size of transaction 4kb -> 6kb

---

src/main/java/com/hedera/hashgraph/sdk/HederaReceiptStatusException.java
src/main/java/com/hedera/hashgraph/sdk/HederaStatusException.java
src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java
src/main/java/com/hedera/hashgraph/sdk/crypto/ed25519/Ed25519PublicKey.java
src/main/java/com/hedera/hashgraph/sdk/file/FileAppendTransaction.java
src/main/java/com/hedera/hashgraph/sdk/file/FileContentsQuery.java
src/main/java/com/hedera/hashgraph/sdk/file/FileCreateTransaction.java
src/main/java/com/hedera/hashgraph/sdk/file/FileDeleteTransaction.java
src/main/java/com/hedera/hashgraph/sdk/file/FileInfoQuery.java
src/main/java/com/hedera/hashgraph/sdk/file/FileUpdateTransaction.java
src/test/java/com/hedera/hashgraph/sdk/file/FileCreateTransactionTest.java
src/test/java/com/hedera/hashgraph/sdk/integration_tests/FileTransactionsTest.java

also fixes `TransactionReceiptQuery` not waiting for consensus
closes #373
closes #374

document file transactions and add E2E test for files

---

examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSubWithSubmitKey.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/CreateSimpleContract.java

Updated examples to successfully run

Example fixes

---

examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSub.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSubChunked.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSubWithSubmitKey.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/CreateAccount.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/CreateAccountThresholdKey.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/CreateFile.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/CreateSimpleContract.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/CreateStatefulContract.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/DeleteAccount.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/DeleteFile.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/GetAccountBalance.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/GetAddressBook.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/GetFileContents.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/MultiAppTransfer.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/TopicWithAdminKey.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/TransferCrypto.java
examples/src/main/java/com/hedera/hashgraph/sdk/examples/UpdateAccountPublicKey.java

Adds comments to some of the examples, removes unnecessary dependencies on environment variables, adds sleep between topic creation and subscription where missing

Fix / update examples

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Node.java

Issue #450 - Convert sort to Java7 API

---

examples/src/main/java/ClientFromFileExample.java
examples/src/main/resources/client-config-with-operator.json
examples/src/main/resources/client-config.json

feat: Added client from config file with nodes example

---

sdk/src/integrationTest/java/TransactionIntegrationTest.java

feat: Added [to|from]Bytes tests, along with AddSignature test

---

sdk/src/integrationTest/java/AccountBalanceIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountBalance.java

feat: Added token decimal support to AccountBalance

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Node.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Query.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java

WIP: refactor: refactoring Client to be thread safe

---

sdk/src/main/java/com/hedera/hashgraph/sdk/ChunkedTransaction.java

Chore: removed some unnecessary .thenCompose() calls from ChunkedTransaction::executeAllAsync()

---

sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceiptQuery.java

fix: `TransactionReceiptQuery` error handling

---

SDK_ANATOMY.md

docs: Added SDK_ANATOMY.md

---

sdk/src/main/java/com/hedera/hashgraph/sdk/AccountBalanceQuery.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountCreateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountDeleteTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountId.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountInfoQuery.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountRecordsQuery.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountStakersQuery.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountUpdateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractByteCodeQuery.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractCallQuery.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractCreateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractDeleteTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractExecuteTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractInfoQuery.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractUpdateTransaction.java

WIP:feat: adding null checking to most parameters

---

build.gradle
executable-processor/src/main/java/com/hedera/hashgraph/sdk/FunctionalExecutableProcessor.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ChunkedTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractCreateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionResult.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractId.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
sdk/src/main/java/com/hedera/hashgraph/sdk/FeeSchedule.java
sdk/src/main/java/com/hedera/hashgraph/sdk/FileAppendTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/FileCreateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/KeyList.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Mnemonic.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java
sdk/src/main/java/com/hedera/hashgraph/sdk/PrivateKey.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Query.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleCreateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleId.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleInfo.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleSignTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenBurnTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TopicMessageSubmitTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionId.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceipt.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceiptQuery.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java

chore: getting rid of some compiler warnings

---

sdk/src/integrationTest/java/ClientIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java

Sign on demand

---

sdk/src/integrationTest/java/AccountBalanceIntegrationTest.java
sdk/src/integrationTest/java/ScheduleCreateIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountBalance.java

fix: fix misc bugs

---

examples/src/main/java/CreateAccountThresholdKeyExample.java

fix: CreateAccountThresholdKeyExample now uses public keys

---

build.gradle
example-android/app/build.gradle
example-android/build.gradle
examples/build.gradle
executable-processor/build.gradle
sdk/build.gradle

fix: fixed gradle file so that VSCode is aware of generated code

---

sdk/src/main/java/com/hedera/hashgraph/sdk/ChunkedTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java

fix: fixed bugs in sign-on-demand

---

sdk/src/integrationTest/java/NftMetadataGenerator.java
sdk/src/integrationTest/java/TokenBurnIntegrationTest.java
sdk/src/integrationTest/java/TokenCreateIntegrationTest.java
sdk/src/integrationTest/java/TokenFeeScheduleUpdateIntegrationTest.java
sdk/src/integrationTest/java/TokenInfoIntegrationTest.java
sdk/src/integrationTest/java/TokenMintIntegrationTest.java
sdk/src/integrationTest/java/TokenNftInfoIntegrationTest.java
sdk/src/integrationTest/java/TokenNftTransferIntegrationTest.java
sdk/src/integrationTest/java/TokenWipeIntegrationTest.java
sdk/src/integrationTest/java/TransactionIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/RequestType.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Status.java
sdk/src/main/proto/ResponseCode.proto

chore: NFT and HIP 18 tests are now correct, and misc improvements

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Status.java

fix: add missing Status values and fix Javadoc

---

sdk/src/integrationTest/java/ScheduleCreateIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Query.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceipt.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TransferTransaction.java

Fixes a bug in `TransferTransaction::build()` that broke scheduled token transfers.
Adds an integration test that would have detected this bug.
Improves `Query::getCost()`
Some other misc improvements.
**Checklist**

fix: fixed bug that broke scheduled token transfers 

---

sdk/src/integrationTest/java/FileAppendIntegrationTest.java
sdk/src/integrationTest/java/IntegrationTestEnv.java
sdk/src/integrationTest/java/TopicMessageSubmitIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/EntityIdHelper.java

improved tests to better catch bugs in chunked transactions, and improved EntityIdHelper exceptions

fix: improved tests and exceptions

---

sdk/src/main/java/com/hedera/hashgraph/sdk/CustomFee.java
sdk/src/main/java/com/hedera/hashgraph/sdk/CustomFixedFee.java
sdk/src/main/java/com/hedera/hashgraph/sdk/CustomFractionalFee.java
sdk/src/main/java/com/hedera/hashgraph/sdk/FeeDataType.java
sdk/src/main/java/com/hedera/hashgraph/sdk/FeeSchedules.java
sdk/src/main/java/com/hedera/hashgraph/sdk/NftId.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenFeeScheduleUpdateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenInfo.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenNftInfoQuery.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenNftTransfer.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenSupplyType.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenType.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TransferTransaction.java

Chore: warning removal and bug fixes

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Mnemonic.java
sdk/src/main/java/com/hedera/hashgraph/sdk/PrivateKey.java
sdk/src/test/java/com/hedera/hashgraph/sdk/MnemonicTest.java

fix: fixed legacyDerive, added legacyDerive and mnemonic 3 tests

---

scripts/premade/FeeDataType-0.txt
scripts/premade/FeeDataType-2.txt
scripts/premade/FeeDataType-4.txt
scripts/premade/FeeDataType-6.txt
scripts/update_protobufs.py
sdk/src/integrationTest/java/TokenCreateIntegrationTest.java
sdk/src/integrationTest/java/TokenFeeScheduleUpdateIntegrationTest.java
sdk/src/integrationTest/java/TokenMintIntegrationTest.java
sdk/src/integrationTest/java/TokenTransferIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/FeeDataType.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Status.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenCreateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenFeeScheduleUpdateTransaction.java
sdk/src/main/proto/BasicTypes.proto
sdk/src/main/proto/CustomFees.proto
sdk/src/main/proto/ResponseCode.proto
sdk/src/main/proto/TokenBurn.proto
sdk/src/main/proto/TokenCreate.proto
sdk/src/main/proto/TokenDissociate.proto
sdk/src/main/proto/TokenGetAccountNftInfos.proto
sdk/src/main/proto/TokenGetNftInfos.proto
sdk/src/main/proto/TokenMint.proto
sdk/src/main/proto/TokenUpdate.proto
sdk/src/main/proto/TokenWipeAccount.proto
sdk/src/test/java/com/hedera/hashgraph/sdk/Ed25519PrivateKeyTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TokenFeeScheduleUpdateTransactionTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TopicUpdateTransactionTest.snap

- Remove `addCustomFee()` methods.
- Enable custom fees tests.
- Add more custom fee integration tests.
- Add support for new response codes. 
- fix broken unit tests.
Fixes #568

Chore: prepare for custom fees release

---

src/main/java/com/hedera/hashgraph/sdk/crypto/Mnemonic.java
src/main/java/com/hedera/hashgraph/sdk/crypto/ed25519/Ed25519PrivateKey.java
src/test/java/com/hedera/hashgraph/sdk/ScheduleTest.java
src/test/java/com/hedera/hashgraph/sdk/crypto/MnemonicTest.java

fix: legacy derive, and mnemonic 3derive, added tests

---

sdk/src/integrationTest/java/NftMetadataGenerator.java
sdk/src/integrationTest/java/TokenBurnIntegrationTest.java
sdk/src/integrationTest/java/TokenMintIntegrationTest.java
sdk/src/integrationTest/java/TokenNftInfoIntegrationTest.java
sdk/src/integrationTest/java/TokenNftTransferIntegrationTest.java
sdk/src/integrationTest/java/TokenWipeIntegrationTest.java

**Issues**
Fixes #575
**Checklist**

test: add more NFT tests

---

sdk/src/integrationTest/java/TopicMessageSubmitIntegrationTest.java

test: add a regression test

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java

Fixes a bug that caused an incorrect transaction fee to appear in ScheduleInfo.
Fixes #589
**Checklist**

Fix: correct transaction fee from ScheduleInfo

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java

fix: fixed problem that was causing a unit test failure

---

CHANGELOG.md
sdk/src/main/java/com/hedera/hashgraph/sdk/TopicMessageQuery.java

fix: fix bug in topicMessageQuery

---

sdk/src/test/java/com/hedera/hashgraph/sdk/TopicMessageQueryTest.java

Adds a regression test to detect #600
**Checklist**

test: add regression test for topic message retry

---

sdk/src/integrationTest/java/TokenCreateIntegrationTest.java

Improve/simplify the royalty fee test
**Checklist**

test: clean up royalty fee test

---

.github/workflows/master.yml
.github/workflows/testnet.yml
CONTRIBUTING.md
README.md
sdk/build.gradle

- Fix CI not running
- Fix references to master
**Checklist**

Re-enable CI by fixing references to master

---

.github/workflows/testnet.yml
build.gradle
sdk/build.gradle

- Add [SonarCloud](https://sonarcloud.io/dashboard?id=hashgraph_hedera-sdk-java) check
- Change integrationTest to conditionally run only if operator environment variables are present
- Fix code coverage not generating report
Results will appear once main branch is analyzed. Future PRs will compare changes against main to track new code smells.
**Checklist**

Add SonarCloud check

---

.github/workflows/testnet.yml
sdk/src/integrationTest/java/IntegrationTestEnv.java

fix: change test env client construction

---

sdk/src/test/java/com/hedera/hashgraph/sdk/AccountIdTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/ClientTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/NftIdTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TestServer.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TestService.java

* closes client during unit tests to get rid of scary-looking warning
* Add a mocking framework to be used in some unit tests

test: close client, add mocking framework

---

README.md
examples/build.gradle
sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java
sdk/src/test/java/com/hedera/hashgraph/sdk/MockingTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TestResponse.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TestServer.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TestService.java

* Update the readme to reflect updates to SLF4J
* Suppress a bunch of useless compiler warnings in examples.
* Flesh out the mock testing framework for unit tests.
* Add some mocking tests.
**Checklist**

test: add server-mocking tests

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java

fix: fix CI (again (again (again)))

---

.github/workflows/testnet.yml

feat: add CI step that only compiles the SDK, examples, and tests

---

sdk/src/integrationTest/java/AutomaticAssociationTest.java

Add integration testing for automatic token association
Fixes #669
**Checklist**

test: automatic token association

---

sdk/src/main/java/com/hedera/hashgraph/sdk/AccountUpdateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/RequestType.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Status.java
sdk/src/main/proto/basic_types.proto
sdk/src/main/proto/crypto_create.proto
sdk/src/main/proto/crypto_get_info.proto
sdk/src/main/proto/crypto_update.proto
sdk/src/main/proto/network_get_execution_time.proto
sdk/src/main/proto/network_service.proto
sdk/src/main/proto/query.proto
sdk/src/main/proto/response.proto
sdk/src/main/proto/response_code.proto
sdk/src/main/proto/token_service.proto

chore: update automatic token association protobufs

---

sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNetwork.java

fix: remove old doc comments

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Status.java
sdk/src/main/proto/response_code.proto

Adds new response codes
Fixes #766
**Checklist**

chore: add new smart contract response codes

---

sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNodeAddress.java

fix: remove use of named regex groups to support older versions of Android

---

sdk/src/integrationTest/java/IntegrationTestEnv.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java

chore: add previewnet addresses, make tweaks to how multiple IPs per node works

---

CHANGELOG.md
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionResult.java

fix: expose createdContractIds in ContractFunctionResult

---

CHANGELOG.md
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountBalance.java

fix: make AccountBalance.[to|from]Bytes() public

---

sdk/src/main/java/com/hedera/hashgraph/sdk/FileId.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenId.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TopicId.java

Added to and from solidity methods from file ID, topic ID, and token ID
Fixes # **https://github.com/hashgraph/hedera-sdk-java/issues/837**
**Checklist**

Add to/from solidity methods

---

sdk/src/integrationTest/java/ContractBytecodeIntegrationTest.java
sdk/src/integrationTest/java/ContractCallIntegrationTest.java
sdk/src/integrationTest/java/ContractCreateIntegrationTest.java
sdk/src/integrationTest/java/ContractDeleteIntegrationTest.java
sdk/src/integrationTest/java/ContractExecuteIntegrationTest.java
sdk/src/integrationTest/java/ContractInfoIntegrationTest.java
sdk/src/integrationTest/java/ContractUpdateIntegrationTest.java
sdk/src/integrationTest/java/SystemIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleCreateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java

Fixes schedule create transaction and makes integration tests pass again
**Checklist**

fix: schedule create transaction and integration tests

---

sdk/src/test/java/com/hedera/hashgraph/sdk/NftIdTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/NftIdTest.snap

test: add some NftId tests

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java
sdk/src/test/java/com/hedera/hashgraph/sdk/Mocker.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TestServer.java

Chore: Network adjustments

---

sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java

fix: node backoff propogation

---

CHANGELOG.md
sdk/src/integrationTest/java/AccountInfoIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountInfoFlow.java

Feat: add AccountInfoFlow

---

examples/src/main/java/CreateSimpleContractExample.java
sdk/src/integrationTest/java/ContractCreateFlowIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractCreateFlow.java
sdk/src/test/java/com/hedera/hashgraph/sdk/MockingTest.java

Fixes contract create flow.
Fixes #905
**Checklist**

Fix: contract create flow

---

sdk/src/integrationTest/java/AccountBalanceIntegrationTest.java
sdk/src/integrationTest/java/AccountCreateIntegrationTest.java
sdk/src/integrationTest/java/AutomaticAssociationTest.java
sdk/src/integrationTest/java/ClientIntegrationTest.java
sdk/src/integrationTest/java/ContractCallIntegrationTest.java
sdk/src/integrationTest/java/ContractCreateFlowIntegrationTest.java
sdk/src/integrationTest/java/TopicMessageIntegrationTest.java

test: fix integration tests

---

CHANGELOG.md
examples/src/main/java/ConstructClientExample.java
examples/src/main/java/CreateSimpleContractExample.java
examples/src/main/java/CreateStatefulContractExample.java
examples/src/main/java/CreateTopicExample.java
examples/src/main/java/DeleteAccountExample.java
examples/src/main/java/GetAccountInfoExample.java
examples/src/main/java/MultiSigOfflineExample.java
examples/src/main/java/ScheduleIdenticalTransactionExample.java
examples/src/main/java/ScheduledTransactionMultiSigThresholdExample.java
examples/src/main/java/SignTransactionExample.java

The examples across the SDK's should match.
* Added / Fixed examples as needed
Fixes #709 
**Checklist**

709 examples update

---

examples/src/main/java/AccountAliasExample.java
sdk/src/integrationTest/java/AccountAllowanceIntegrationTest.java
sdk/src/integrationTest/java/AccountBalanceIntegrationTest.java
sdk/src/integrationTest/java/AccountCreateIntegrationTest.java
sdk/src/integrationTest/java/AutomaticAssociationTest.java
sdk/src/integrationTest/java/ClientIntegrationTest.java
sdk/src/integrationTest/java/ContractBytecodeIntegrationTest.java
sdk/src/integrationTest/java/ContractCallIntegrationTest.java
sdk/src/integrationTest/java/ContractCreateFlowIntegrationTest.java
sdk/src/integrationTest/java/ContractExecuteIntegrationTest.java
sdk/src/integrationTest/java/FileContentsIntegrationTest.java
sdk/src/integrationTest/java/IntegrationTestEnv.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountAllowanceAdjustTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AddressBookQuery.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionParameters.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionResult.java
sdk/src/main/java/com/hedera/hashgraph/sdk/DelegateContractId.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
sdk/src/main/java/com/hedera/hashgraph/sdk/HederaTrustManager.java
sdk/src/main/java/com/hedera/hashgraph/sdk/LedgerId.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Node.java
sdk/src/main/java/com/hedera/hashgraph/sdk/PrivateKeyECDSA.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenPauseTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenTransfer.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenUnpauseTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionId.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TransferTransaction.java

chore: address sonarcloud issues

---

sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNetwork.java

fix: getNumberOfMostHealthyNodes()

---

build.gradle

chore: remove Jakarta because we don't seem to be using it

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
sdk/src/test/java/com/hedera/hashgraph/sdk/MockingTest.java

Fix: allow users to cancel executeAsync

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java

fix: prevent lost exceptions

---

CHANGELOG.md
sdk/src/main/java/com/hedera/hashgraph/sdk/CustomRoyaltyFee.java

fix: make fallback fee public

---

sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNetwork.java

fix: bug again

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Node.java

chore: clean up where synchronized keyword is used in the SDK

---

sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java

Use the EthereumHash instead of the TransactionHash
Signed-off-by: Danno Ferrin <danno.ferrin@hedera.com>
Fixes #1000
**Checklist**

Return correct EthereumHash

---

sdk/build.gradle
sdk/src/main/java/com/hedera/hashgraph/sdk/EthereumFlow.java
sdk/src/main/java/com/hedera/hashgraph/sdk/EthereumTransactionData.java
sdk/src/main/java/com/hedera/hashgraph/sdk/EthereumTransactionDataEip1559.java
sdk/src/main/java/com/hedera/hashgraph/sdk/EthereumTransactionDataLegacy.java
sdk/src/main/java/com/hedera/hashgraph/sdk/FileAppendTransaction.java
sdk/src/test/java/com/hedera/hashgraph/sdk/EthereumFlowMockTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/EthereumTransactionDataLegacyTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/Function.java
sdk/src/test/java/com/hedera/hashgraph/sdk/Mocker.java
sdk/src/test/java/com/hedera/hashgraph/sdk/MockingTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/RegenerateTransactionIdsTest.java

Signed-off-by: Daniel Akhterov <daniel@launchbadge.com>**Description**:
Fixes #
**Checklist**

feat: implement `EthereumTransactionData`

---

examples/src/main/java/ScheduleExample.java

feat: implement schedule example

---

Taskfile.yml
sdk/src/integrationTest/java/ClientIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
sdk/src/main/java/com/hedera/hashgraph/sdk/HbarUnit.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNodeAddress.java
sdk/src/main/java/com/hedera/hashgraph/sdk/PrivateKey.java
sdk/src/main/java/com/hedera/hashgraph/sdk/SemanticVersion.java
sdk/src/test/java/com/hedera/hashgraph/sdk/MockingTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/PrivateKeyTest.java

Fixes #1041, #1015, #1028, #1029, #1030
**Checklist**

fix: several small issues

---

CHANGELOG.md
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountBalance.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountInfo.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractInfo.java
sdk/src/main/java/com/hedera/hashgraph/sdk/PrngTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/RequestType.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Status.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenNftInfo.java
sdk/src/main/proto/basic_types.proto
sdk/src/main/proto/node_stake_update.proto
sdk/src/main/proto/response_code.proto
sdk/src/main/proto/schedulable_transaction_body.proto
sdk/src/main/proto/transaction_body.proto
sdk/src/main/proto/transaction_record.proto
sdk/src/main/proto/util_prng.proto
sdk/src/test/java/com/hedera/hashgraph/sdk/PrngTransactionTest.snap
sdk/src/test/java/com/hedera/hashgraph/sdk/TokenNftInfoTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TokenNftInfoTest.snap

Fixes #1053
Fixes #1054
Fixes #1060
**Checklist**

Chore: Deprecate tokens and update protos

---

sdk/src/integrationTest/java/TokenCreateIntegrationTest.java
sdk/src/integrationTest/java/TokenInfoIntegrationTest.java
sdk/src/integrationTest/java/TokenUpdateIntegrationTest.java

test: get integration tests working

---

scripts/update_protobufs.py

fix: update_protobufs script now supports overrides

---

sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java

fix: max backoff

---

CHANGELOG.md
examples/src/main/java/GetAddressBookExample.java
sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java

Revert changes to the mirror network
**Checklist**

chore: revert changes to the mirror network

---

.github/workflows/build.yml
sdk/build.gradle

feat: add codecov to build.yml

---

CHANGELOG.md
SDK_ANATOMY.md
examples/src/main/java/GetAddressBookExample.java
sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNode.java
sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNodeAddress.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNode.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Node.java
sdk/src/test/java/com/hedera/hashgraph/sdk/AddressBookQueryMockTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/BaseNodeAddressTest.java

Also renames `Managed*` to `Base*`
Fixes #1099
**Checklist**

feat: enable users to separately control mirror network transport security

---

CHANGELOG.md
sdk/src/test/java/com/hedera/hashgraph/sdk/Ed25519PrivateKeyTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/Ed25519PublicKeyTest.java

test: fix key.is[ECDSA|ED25519]() tests

---

CHANGELOG.md
example-android/app/build.gradle
sdk/build.gradle
sdk/src/main/java/com/hedera/hashgraph/sdk/Pem.java

Fixes #998
May be in need of more tests.
**Checklist**

feat: improved PEM file support

---

CHANGELOG.md
README.md
example-android/app/build.gradle
version.gradle

chore: prepare to release 2.17.4

---

Taskfile.yml

chore: remove references to ExecutableProcessor from taskfile

---

.github/workflows/build.yml
build.gradle
settings.gradle

Fix Sonar showing 0% code coverage
Fixes #1196

chore: try fixing the Sonar code coverage

---

CHANGELOG.md
examples/src/main/java/AccountCreateWithHtsExample.java

This PR adds example for HIP 542 - Account create with HTS
Fixes #1170
**Checklist**

Example HIP-542 #1170

---

CHANGELOG.md
README.md
example-android/app/build.gradle
version.gradle

chore: prepare for 2.17.5 release

---

build.gradle
sdk/build.gradle
sdk/protobuf.gradle

Small changes needed for deployment

chore: fix deployment

---

sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNetwork.java

Makes BaseNetwork.increaseBackoff synchronized
Fixes #1176 
**Checklist**

fix: make BaseNetwork.increaseBackoff synchronized

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java

Allows the user to handle the exceptions when pinging.
Fixes #1178 
**Checklist**

fix: Allow the user to handle exceptions when pinging

---

CHANGELOG.md
README.md
example-android/app/build.gradle
version.gradle

chore: prepare for 2.18.2 release

---

CHANGELOG.md
sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java

fix: rejectedExecutionException under heavy load

---

CHANGELOG.md
sdk/src/integrationTest/java/ContractCreateFlowIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractCreateFlow.java

feat: add freezeWith() and sign() to ContractCreateFlow

---

CHANGELOG.md
sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java

Fix: nodes not clearing when reusing tx

---

CHANGELOG.md
README.md
example-android/app/build.gradle
version.gradle

chore: prepare for 2.19.0 release

---

sdk/src/main/java/com/hedera/hashgraph/sdk/ContractCreateTransaction.java

This PR modifies the ContractCreateTransaction.getBytecode() comment to match the functionality
Fixes #1290 
**Checklist**

ContractCreateTransaction - fix getBytecode() comment

---

CHANGELOG.md
sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java
sdk/src/test/java/com/hedera/hashgraph/sdk/BaseNodeAddressTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/ClientTest.java
sdk/src/test/resources/client-config-with-operator.json

Updates the mirror node endpoints
Fixes #1316 
**Checklist**

fix: update mirror node endpoints

---

CHANGELOG.md
README.md
example-android/app/build.gradle
version.gradle

Release 2.20.0
Fixes #
**Checklist**

Prepare for Release 2.20.0

---

.github/CODEOWNERS
examples/src/main/java/NftAddRemoveAllowancesExample.java
sdk/src/integrationTest/java/NftAllowancesIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountAllowanceAdjustTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountAllowanceApproveTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountAllowanceDeleteTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenNftAllowance.java
sdk/src/test/java/com/hedera/hashgraph/sdk/AllowancesTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/AllowancesTest.snap

<!--
adds delegating spender and functionality to remove allowance for all serials to `AccountAllowanceApproveTX`
Fixes #1322 
Fixes #1323 
**Checklist**

feat: Add delegating spender functionality to AccountAllowanceApproveTX

---

.github/workflows/previewnet.yml
sdk/src/integrationTest/java/IntegrationTestEnv.java

This PR fixes a typo in the previewnet github flow and adds some logging in the Integration test environment.
**Checklist**

Fix preview and testnet builds

---

.github/workflows/previewnet.yml
sdk/src/integrationTest/java/ClientIntegrationTest.java
sdk/src/integrationTest/java/IntegrationTestEnv.java

This PR changes the pingAllBadNetwork test logic in order to fix preview & testnet builds.
**Checklist**

Fix preview & testnet build - pingAllBadNetwork

---

sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNetwork.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
sdk/src/main/java/com/hedera/hashgraph/sdk/LockableList.java
sdk/src/test/java/com/hedera/hashgraph/sdk/ClientCloseTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/ExecutableTest.java

This PR adds noHealthyNodesNetwork test
Fixes #796 
**Checklist**

Retry down nodes - noHealthyNodesNetwork test 

---

sdk/src/test/java/com/hedera/hashgraph/sdk/KeyListTest.java

Adds tests for KeyList
Fixes #1404

Add tests for KeyList

---

sdk/src/test/java/com/hedera/hashgraph/sdk/CustomRoyaltyFeeTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/CustomRoyaltyFeeTest.snap

Adds tests for `CustomRoyaltyFee`
Fixes #1433

add tests for CustomRoyaltyFee

---

sdk/src/main/java/com/hedera/hashgraph/sdk/CustomFractionalFee.java
sdk/src/test/java/com/hedera/hashgraph/sdk/CustomFractionalFeeTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/CustomFractionalFeeTest.snap

Adds tests for `CustomFractionalFee`
Fixes #1424

add tests for CustomFractionalFee

---

sdk/src/test/java/com/hedera/hashgraph/sdk/FeeAssessmentMethodTest.java

Adds tests for `FeeAssessmentMethod`
Fixes #1419 
**Checklist**

add tests for FeeAssessmentMethod

---

sdk/src/test/java/com/hedera/hashgraph/sdk/CustomFixedFeeTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/CustomFixedFeeTest.snap
sdk/src/test/java/com/hedera/hashgraph/sdk/TokenTypeTest.java

Adds tests for `CustomFixedFee`
Fixes #1418 
**Checklist**

add tests for CustomFixedFee

---

sdk/src/test/java/com/hedera/hashgraph/sdk/TokenDeleteTransactionTest.java

Add more unit tests for TokenDeleteTransaction.
Fixes #1437 
**Checklist**

Add more unit tests for TokenDeleteTransaction

---

sdk/src/test/java/com/hedera/hashgraph/sdk/AssessedCustomFeeTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/AssessedCustomFeeTest.snap

Adds more AssessedCustomFee tests
Fixes #1438 
**Checklist**

add more AssessedCustomFee tests

---

sdk/src/test/java/com/hedera/hashgraph/sdk/AccountAllowanceApproveTransactionTest.java

Add more unit tests for `AccountAllowanceApproveTransaction`.
Fixes #1450 
**Checklist**

Add more unit tests for `AccountAllowanceApproveTransaction`

---

sdk/src/test/java/com/hedera/hashgraph/sdk/TokenMintTransactionTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TokenMintTransactionTest.snap

- added more unit tests for `TokenMintTransaction`;
- regenerated test `.snap` file.
Fixes #1451 
**Checklist**

Add more unit tests for `TokenMintTransaction`

---

sdk/src/test/java/com/hedera/hashgraph/sdk/TokenInfoQueryTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TokenInfoQueryTest.snap

- added more unit tests for `TokenInfoQuery`;
- reformatted and rearranged code;
- regenerated test `.snap` file.
Fixes #1468 
**Checklist**

Add more unit tests for `TokenInfoQuery`

---

sdk/src/test/java/com/hedera/hashgraph/sdk/TokenBurnTransactionTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TokenBurnTransactionTest.snap

- added more unit tests for `TokenBurnTransaction`;
- reformatted and rearranged code;
- regenerated test `.snap` file.
Fixes #1466 
**Checklist**

Add more unit tests for `TokenBurnTransaction`

---

sdk/src/main/java/com/hedera/hashgraph/sdk/TokenSupplyType.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TokenSupplyTypeTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TokenSupplyTypeTest.snap

Adds tests for TokenSupplyType
Fixes #1417 
**Checklist**

add tests for TokenSupplyType

---

sdk/src/test/java/com/hedera/hashgraph/sdk/TokenAssociateTransactionTest.java

Adds more tests for `TokenAssociateTransaction`
Fixes #1443 
**Checklist**

Add more tests for TokenAssociateTransaction

---

RELEASE.md
Taskfile.yml

Create RELEASE.md file that explains the steps needed for releasing a new version of the SDK
Fixes #1480

Create RELEASE.md file

---

.github/CODEOWNERS

GitHub CODEOWNERS update (@dikel->@thenswan)

GitHub CODEOWNERS update (@dikel->@thenswan)

---

sdk/src/test/java/com/hedera/hashgraph/sdk/TokenAllowanceTest.java

Added unit tests for `TokenAllowance`.
Fixes #1493
**Checklist**

Add unit tests for `TokenAllowance`

---

sdk/src/integrationTest/java/ContractNonceInfoIntegrationTest.java
sdk/src/integrationTest/java/IntegrationTestEnv.java

Improvements in HIP-729 integration test. Removed temporary solution with hardcoded credentials from `IntegrationTestEnv` and `ContractNonceInfoIntegrationTest`.
Fixes #1519 
**Checklist**

Improvements in HIP-729 integration test

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java

- fixed `ClientTest::testExecuteSyncTimeout` test;
- improved timeout handling.
Fixes #1520 
**Checklist**

Improvements after resolving issue #1497

---

sdk/src/test/java/com/hedera/hashgraph/sdk/TopicMessageSubmitTransactionTest.java

Added unit tests for `TopicMessageSubmitTransaction`.
Fixes #1542
**Checklist**

Add unit tests for `TopicMessageSubmitTransaction`

---

sdk/src/integrationTest/java/ContractFunctionParametersIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionParameters.java

Added `addBooleanArray` function to `ContractFunctionParameters` and integration test for it.
Fixes #1524 
**Checklist**

Add `addBoolArray` function to `ContractFunctionParameters`

---

sdk/src/test/java/com/hedera/hashgraph/sdk/TopicMessageChunkTest.java

Added unit tests for `TopicMessageChunk`.
Fixes #1545 
**Checklist**

Add unit tests for `TopicMessageChunk`

---

sdk/src/test/java/com/hedera/hashgraph/sdk/TopicMessageTest.java

Added unit tests for `TopicMessage`.
Fixes #1540
**Checklist**

Add unit tests for `TopicMessage`

---

CHANGELOG.md
README.md
example-android/app/build.gradle
version.gradle

Prepare for stable release v2.29.0

Prepare for stable release v2.29.0

---

.github/dependabot.yml

This pull request changes the following:
- Adds the `github-actions` package ecosystem configuration to the `dependabot.yml` configuration file.
- Closes #1666

chore: update dependabot configuration to monitor Github Actions

---

CHANGELOG.md
README.md
example-android/app/build.gradle
version.gradle

This PR prepares the codebase for v2.29.2 release.

release: v2.29.2

---

CHANGELOG.md
README.md
example-android/app/build.gradle
version.gradle

This PR prepares the codebase for v2.30.0 release.

release: v2.30.0

---

CHANGELOG.md
README.md
example-android/app/build.gradle
version.gradle

This PR prepares the codebase for v2.31.0 release.

release: v2.31.0

---

CHANGELOG.md
docs/java-app/java-app-quickstart.md
example-android/app/build.gradle
version.gradle

This PR prepares the codebase for v2.32.0 **beta** release.

release: v2.32.0-beta.1

---

CHANGELOG.md
docs/java-app/java-app-quickstart.md
example-android/app/build.gradle
version.gradle

This PR prepares the codebase for v2.32.0 release.

release: v2.32.0

---

examples/README.md

This PR adds a small improvement for HIP-745 docs related to its example.

docs: improve HIP-745 docs

---

sdk/src/integrationTest/java/TokenAssociateIntegrationTest.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenRelationship.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TokenRelationshipTest.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TokenRelationshipTest.snap

This PR adds `decimal` field to `TokenRelationship` class.
Closes #1822

feat: add decimal field to TokenRelationship class

---

sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeService.java

This PR improves documentation for methods in `MirrorNodeService` based on comment https://github.com/hashgraph/hedera-sdk-java/pull/1698#discussion_r1611462238
Closes #1824

docs: improve documentation for methods in MirrorNodeService

---

examples/src/main/java/ContractNoncesExample.java

This PR fixes default value for a network in HIP-729 example.

fix: default value for a network in HIP-729 example

---

sdk/src/main/java/com/hedera/hashgraph/sdk/TokenRelationship.java

revert: undeprecate TokenRelationship.symbol

---

CHANGELOG.md
docs/java-app/java-app-quickstart.md
example-android/app/build.gradle
version.gradle

This PR prepares the codebase for v2.34.0 release.

release: v2.34.0

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Key.java
sdk/src/test/java/com/hedera/hashgraph/sdk/KeyTest.java

Add `fromBytes` function to `Key`
Fixes #
**Checklist**

feat: add `fromBytes` function to `Key`

---

Taskfile.yml

This PR fixes address book related tasks in `Taskfile.yml`.
Closes #1885

fix: address book related tasks in Taskfile.yml

---

gradle/plugins/src/main/kotlin/com.hedera.gradle.publish.gradle.kts

This PR updates `developers` section under `MavenPublication`.
Closes #1896

chore: update developers section under MavenPublication

---

.github/dependabot.yml

This PR updates the dependabot config to handle the updated gradle setup
Fixes #
**Checklist**

chore: update directory for gradle in dependabot

---

sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/TokenUpdateNftsIntegrationTest.java

chore: fix e2e tests

---

tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/AccountService.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/AccountDeleteParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/AccountUpdateParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/response/AccountResponse.java

Fixes #1931 #1735
**Checklist**

feat(TCK): Implement Account Update/Delete

---

sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionParameters.java
sdk/src/test/java/com/hedera/hashgraph/sdk/ContractFunctionParametersTest.java

adds addBytes4 and addBytes4Array to ContractFunctionParameters class
Fixes #
- fixes #1650 
**Checklist**

feat(ContractFunctionParameters): adds addBytes4 and addBytes4Array

---

sdk/src/main/java/com/hedera/hashgraph/sdk/InstantConverter.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenCreateTransaction.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/AccountService.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/SdkService.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/TokenService.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/CustomFee.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/TokenCreateParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/response/TokenResponse.java
tck/src/test/java/com/hedera/hashgraph/tck/methods/sdk/SdkServiceTest.java

Implements token create method
Fixes #2020
**Checklist**

feat(TCK): Implement `TokenCreate`

---

.github/workflows/build.yml

Update per Q3 audit findings
Related to #1909 
**Checklist**

ci: Update per Q3 audit findings

---

sdk/src/main/java/com/hedera/hashgraph/sdk/TokenUpdateTransaction.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/TokenService.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/TokenUpdateParams.java

Implement `updateToken` method in the tck.
Fixes #
TCK tests are passing
**Checklist**

feat(TCK): `updateToken` method

---

.github/workflows/build.yml

Downgrade codecov-action to a stable version
Fixes #2118
**Checklist**

ci: Downgrade codecov-action to a stable version

---

docs/sdk/developer-guide.md

Resolves the following open item in #1794:
- Add more docs for the Gradle build, in particular for adding/modifying dependencies
#1794

chore: extend documentation of Gradle build

---

example-android/app/build.gradle.kts
example-android/app/src/main/AndroidManifest.xml
example-android/app/src/main/java/org/hiero/android_example/MainActivity.kt
example-android/app/src/main/java/org/hiero/android_example/ui/main/AccountBalanceFragment.kt
example-android/app/src/main/java/org/hiero/android_example/ui/main/CryptoTransferFragment.kt
example-android/app/src/main/java/org/hiero/android_example/ui/main/PrivateKeyFragment.kt
example-android/app/src/main/java/org/hiero/android_example/ui/main/SectionsPagerAdapter.kt
example-android/gradle/module.properties
hiero-dependency-versions/build.gradle.kts
settings.gradle.kts

**Related issue(s)**: https://github.com/hashgraph/hedera-sdk-java/issues/2017
Fixes #
**Checklist**

chore: Rename android examples to Hiero

---

settings.gradle.kts
tck/build.gradle.kts

https://github.com/hiero-ledger/hiero-gradle-conventions/releases/tag/v0.3.1
**Checklist**

chore: update hiero-gradle-conventions

---

.github/workflows/build.yml
sdk/src/main/java/com/hedera/hashgraph/sdk/AccountAllowanceApproveTransaction.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/AccountService.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/account/AccountAllowanceParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/account/AllowanceParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/response/AccountAllowanceResponse.java
tck/src/main/java/com/hedera/hashgraph/tck/util/JSONRPCParamParser.java

fixes:
https://github.com/hiero-ledger/hiero-sdk-java/issues/2184

feat: introduce new AccountAllowance endpoints

---

tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/AccountService.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/account/AccountCreateParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/account/AccountUpdateParams.java
tck/src/test/java/com/hedera/hashgraph/tck/methods/sdk/param/AccountCreateParamsTest.java

Fixes:
https://github.com/hiero-ledger/hiero-sdk-tck/issues/284

#284 fix account params

---

.github/workflows/build.yml
sdk/src/main/java/com/hedera/hashgraph/sdk/TokenCreateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/TopicCreateTransaction.java
sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/TokenCreateIntegrationTest.java
sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/TopicCreateIntegrationTest.java

Fixes #
https://github.com/hiero-ledger/hiero-sdk-java/issues/2230
https://github.com/hashgraph/hedera-improvement-proposal/pull/1021
**Checklist**

feat: introduce new HIP-1021

---

scripts/update_protobufs.py

The services repo is now moved to Hiero so we need to update the path to the protobuf files to https://github.com/hiero-ledger/hiero-consensus-node/
Fixes #2226
**Checklist**

chore: update protos path

---

tck/src/main/resources/application.yml

chore(TCK): change port to 8544

---

sdk/src/main/java/com/hedera/hashgraph/sdk/TopicCreateTransaction.java
sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/TopicCreateIntegrationTest.java

revert: automatic setting of autorenew account for topic create

---

sdk/src/main/java/com/hedera/hashgraph/sdk/EvmAddress.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/AccountService.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/CommonTransactionParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/transfer/HbarTransferParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/transfer/NftTransferParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/transfer/TokenTransferParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/transfer/TransferCryptoParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/transfer/TransferParams.java

Fixes #
https://github.com/hiero-ledger/hiero-sdk-java/issues/2253
**Checklist**

feat(TCK): json rpc for transfer transaction

---

sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNode.java

chore: enable gRPC retries

---

sdk/src/main/java/com/hedera/hashgraph/sdk/TopicCreateTransaction.java
sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/TopicCreateIntegrationTest.java

Fixes #
https://github.com/hiero-ledger/hiero-sdk-java/issues/2299
**Checklist**

chore: enable HIP-1021

---

tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/TokenService.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/token/TokenAirdropParams.java
tck/src/main/java/com/hedera/hashgraph/tck/util/AirdropUtils.java

feat(TCK): Introduce `tokenAirdrop` endpoint

---

sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java
sdk/src/test/java/com/hedera/hashgraph/sdk/ClientTest.java

Fixes #
https://github.com/hiero-ledger/hiero-sdk-java/issues/2317
**Checklist**

chore: append address book on node creation from network entry

---

sdk/src/main/java/com/hedera/hashgraph/sdk/ChunkedTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/FileAppendTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java
sdk/src/test/java/com/hedera/hashgraph/sdk/TransactionTest.java

chore: determine current size of transaction

---

.github/workflows/release-artifacts.yml

Update central publishing credentials names

---

sdk/src/main/java/com/hedera/hashgraph/sdk/AccountUpdateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/FileCreateTransaction.java
sdk/src/main/java/com/hedera/hashgraph/sdk/FileUpdateTransaction.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/AccountService.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/FileService.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/file/FileAppendParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/file/FileCreateParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/file/FileDeleteParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/file/FileUpdateParams.java
tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/response/FileResponse.java

tck endpoints for FileAppend/Create/Delete/Update
Fixes https://github.com/hiero-ledger/hiero-sdk-java/issues/2405
**Checklist**

introduce tck endpoints for FileAppend/Create/Delete/Update

---

examples/README.md

Fixed Readme link not working issue

Fixed Readme issue #2426
