- src/main/java/com/hedera/sdk/account/HederaAccount.java
- src/main/java/com/hedera/sdk/common/Utilities.java
- src/main/java/com/hedera/sdk/contract/HederaContract.java
- src/main/java/com/hedera/sdk/file/HederaFile.java
- src/main/java/com/hedera/sdk/node/HederaNode.java
- src/main/java/com/hedera/sdk/query/HederaQueryBySolidityID.java
- src/main/java/com/hedera/sdk/transaction/HederaTransaction.java
#9 Additional validation for node, txQueryDefaults, txQueryDefaults.node, txQueryDefaults.node.getAccountID and txQueryDefaults.payingKeyPair.
Generic utilities created to validate an accountID and check for a null object which throw IllegalStateException with an explanation message in the event validation fails.
Utilities used in HederaAccount, HederaContract, HederaFile, HederaNode, HederaQueryBySolidityID and HederaTransaction to perform the necessary validation.
> Added validation

- src/main/java/com/hedera/sdk/account/HederaAccount.java
The methods fail when they are called before any other method that sets the `this.node` property.
> Update input validations

- sdk/src/main/java/com/hedera/sdk/common/Utilities.java
At first I was wondering how 16 bytes = 64 bits, but unless my understanding of how SecureRandom.nextLong works is wrong, it isn't necessary anyway.
> Remove redundant nextBytes call.

- examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/CreateSimpleContract.java
- examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/CreateStatefulContract.java
- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- src/main/java/com/hedera/hashgraph/sdk/TransactionRecordQuery.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountClaimQuery.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountRecordsQuery.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountStakersQuery.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractBytecodeQuery.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractCallQuery.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractExecuteTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractInfoQuery.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractRecordsQuery.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractUpdateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileUpdateTransaction.java
- src/test/groovy/com/hedera/hashgraph/sdk/contract/ContractExecuteTransactionTest.groovy
- src/test/groovy/com/hedera/hashgraph/sdk/contract/ContractUpdateTransactionTest.groovy
closes #97 
cc @mehcode @bchevallereau
> Fix naming inconsistencies with `set{Entity}()` vs `set{Entity}Id()`

- examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/TransferCrypto.java
- src/main/java/com/hedera/hashgraph/sdk/HederaException.java
- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java
closes #99
@gregscullard we're not sure whether `setGenerateRecord(true)` is required or not because the testnets spuriously return empty records regardless of whether or not it is set:
cc @mehcode
> waiting for record involves a different response code

- src/main/java/com/hedera/hashgraph/sdk/SystemDeleteTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/SystemUndeleteTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountAddClaimTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountBalanceQuery.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountClaimQuery.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountCreateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountDeleteClaimTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountDeleteTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountUpdateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/account/CryptoTransferTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractCreateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractExecuteTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractUpdateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileAppendTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileCreateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileDeleteTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileUpdateTransaction.java
closes #101 
This introduces the ability to generate unsigned protobufs and byte arrays through the use of `unsigned` variants of `Validate`, `toProto`, and `toBytes`
> enables generation of a transaction protobuf that hasnt been signed

- src/main/java/com/hedera/hashgraph/sdk/HederaCall.java
- src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- src/main/java/com/hedera/hashgraph/sdk/TransactionId.java
cc @mehcode @mike-burrage-hedera
closes #130
> Mitigate duplicate transaction errors when calling `Transaction.executeForRecordAsync()`

- src/main/java/com/hedera/hashgraph/sdk/FunctionResult.java
- src/test/java/com/hedera/hashgraph/sdk/FunctionResultTest.java
closes #150
@gregscullard I added the following, are there any important ones that we're missing?
* `getBool()`
* `getBytes()`
* `getLong()`
* `getBigInt()`
* `getAddress()`
* `getRawValue()` (returning a 32-byte string)
I'm on the fence about returning `ByteString` in these APIs; converting to a byte array unfortunately requires a copy. It is possible to return a `java.nio.ByteBuffer` but reading from that also requires copying.
I'm also on the fence about keeping the overloaded `get*()` methods which return the 0th value interpreted as that type; I'm not sure how much convenience they add over doing `get[Bool, etc.](0)`.
cc @mehcode
> FunctionResult: implement more result getters

- src/main/java/com/hedera/hashgraph/sdk/IdUtil.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountId.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractId.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileId.java
- src/test/java/com/hedera/hashgraph/sdk/IdUtilTest.java
Pull request for [Issue #163](https://github.com/hashgraph/hedera-sdk-java/issues/163)
I created an IdUtil file that holds one method for parsing ID strings. I then added a fromString method for both ContractId and FileId that implements this parsing function. I also refactored the existing AccountId.fromString method to use the parsing function as well. There is a test file included that passes for all four methods.
I recognize that having a separate IdUtil file for a 12 line method may be overkill. Ideally, I'd like to pull more of the fromString functionality into the same static utility method but the way each ID is uniquely built makes that impractical. I'm interested if there is a better solution that can be suggested.
> Added IdUtils and fromString methods

- src/main/java/com/hedera/hashgraph/sdk/CallParams.java
Incorrect tag for the type to the Solidity Interface. It needs to go as bytes32, not bytes[32]
> Following up on issue #177.

- src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java
* deprecates `Transaction[Builder].executeForRecord*()` because querying a record has a cost separate from executing the transaction and should be done in a subsequent step
* deprecates `QueryBuilder.setPaymentDefault()` (no args) because we need to request COST_ANSWER from the node and the function's signature is insufficient to represent that operation
> deprecate operations with hidden/unclear costs

- src/main/java/com/hedera/hashgraph/sdk/Client.java
- src/main/java/com/hedera/hashgraph/sdk/HederaCall.java
- src/main/java/com/hedera/hashgraph/sdk/HederaThrowable.java
- src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountBalanceQuery.java
Only works if:
* an operator ID and key are set on the Client
* Client.setMaxQueryPayment is used and the cost does not exceed it (we figure this should eliminate surprises for costly queries and the default is 0 so this behavior is opt-in only)
cc @mehcode @kenthejr @mike-burrage-hedera @paulmadsenhed
> automatically fetch COST_ANSWER for queries and set payments

- examples/src/main/java/com/hedera/hashgraph/sdk/examples/ExampleHelper.java
This broke when I added `openjdk8` in the Travis config but wouldn't say why: https://travis-ci.org/hashgraph/hedera-sdk-java/jobs/584817474
I'm inclined to say it's an issue with Maven 3.6.0 because it works fine with 3.6.2 on my machine.
> fix example compilation on JDK 8

- src/main/java/com/hedera/hashgraph/sdk/Client.java
- src/test/java/com/hedera/hashgraph/sdk/TransactionReceiptQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/TransactionRecordQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/account/AccountAddClaimTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/account/AccountClaimQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/account/AccountCreateTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/account/AccountDeleteClaimTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/account/AccountDeleteTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/account/AccountInfoQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/account/AccountRecordsQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/account/AccountStakersQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/account/AccountUpdateTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/account/CryptoTransferTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/contract/ContractBytecodeQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/contract/ContractCallQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/contract/ContractCreateTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/contract/ContractExecuteTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/contract/ContractInfoQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/contract/ContractRecordsQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/contract/ContractUpdateTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/file/FileAppendTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/file/FileContentsQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/file/FileCreateTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/file/FileDeleteTransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/file/FileInfoQueryTest.java
- src/test/java/com/hedera/hashgraph/sdk/file/FileUpdateTransactionTest.java
also explicitly set fees in all the serialization tests so changes to the default fee don't break them
> Client: set DEFAULT_MAX_TXN_FEE to 1 hbar

- src/main/java/com/hedera/hashgraph/sdk/Client.java
- src/main/java/com/hedera/hashgraph/sdk/GetByKeyQuery.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountAddClaimTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountCreateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountInfo.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountUpdateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/account/Claim.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractCreateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractId.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractInfo.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractUpdateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/crypto/KeyList.java
- src/main/java/com/hedera/hashgraph/sdk/crypto/PublicKey.java
- src/main/java/com/hedera/hashgraph/sdk/crypto/ThresholdKey.java
- src/main/java/com/hedera/hashgraph/sdk/crypto/ed25519/Ed25519PublicKey.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileCreateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileInfo.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileUpdateTransaction.java
- src/test/java/com/hedera/hashgraph/sdk/crypto/ed25519/Ed25519PublicKeyTest.java
This fixes compatibility with Android (static interface methods require API level 24) and fixes an incongruency with the JS SDK.
Breakage should be mostly due to the rename unless people were implementing the interface for their own class.
> (breaking) rename `Key` to `PublicKey` and make it an abstract class

- src/main/java/com/hedera/hashgraph/sdk/SolidityUtil.java
- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountCreateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountId.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountInfo.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountInfoQuery.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractId.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractInfo.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractInfoQuery.java
- src/main/java/com/hedera/hashgraph/sdk/crypto/PublicKey.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileId.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileInfo.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileInfoQuery.java
- src/test/java/com/hedera/hashgraph/sdk/IdUtilTest.java
- src/test/java/com/hedera/hashgraph/sdk/TransactionTest.java
- src/test/java/com/hedera/hashgraph/sdk/account/AccountInfoTest.java
- src/test/java/com/hedera/hashgraph/sdk/contract/ContractInfoTest.java
- src/test/java/com/hedera/hashgraph/sdk/file/FileInfoTest.java
This refactors some objects to deprecate getters in favor of `public final` fields to improve usability and pave the way for supporting serialization with [Jackson](https://github.com/FasterXML/jackson). This also brings these classes more in line with their equivalents in the Javascript SDK.
* `AccountId`, `ContractId`, and `FileId` had their `getShardNum()` and `getRealmNum()` getters deprecated and `shard`/`realm` fields provided instead. Same with `getAccountNum()`/`getContractNum()`/`getFileNum()`, respectively.
* `Transaction.getTransactionId()` has been deprecated in favor of a new `id` field
* `AccountInfo`, `ContractInfo` and `FileInfo` have had all their getter methods deprecated in favor of public fields in the same fashion as the above.
> Refactor some objects into POJOs

- src/main/java/com/hedera/hashgraph/sdk/Backoff.java
- src/main/java/com/hedera/hashgraph/sdk/HederaCall.java
- src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/ThreadUtil.java
- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/TransactionReceiptQuery.java
closes #231
* `Transaction.execute()` and `Transaction.executeAsync()` (and same methods on `TransactionBuilder` will retry if they get `BUSY` until the `validDuration` of the transaction elapses
* `TransactionReceiptQuery` (and thus `Transactinon.queryReceipt()` and `Transaction.queryReceiptAsync()`) will retry on `BUSY`, `OK` and `UNKNOWN` until 5 minutes elapses (maximum value for `validDuration` plus the 3 minutes that the receipt exists for)
* These timeouts can be overridden by the user by calling overloaded methods which take a `Duration` as their last argument; this only times-out the retry process itself, not any blocking calls internally, so may not be exact.
> implement retry with backoff for `BUSY` on `HederaCall.execute[Async]()`

- pom.xml
- src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
Fixes behavior of `Transaction.queryReceipt()` to align with expectations.
> make `Transaction[Receipt, Record]Query` always throw on `UNKNOWN`

- examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/GetAddressBook.java
- examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/TransferCrypto.java
- examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/UpdateAccountPublicKey.java
- examples/src/main/java/com/hedera/hashgraph/sdk/examples/simple/CreateAccount.java
- examples/src/main/java/com/hedera/hashgraph/sdk/examples/simple/TransferCrypto.java
- src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java
rename `Transaction.query*()` to `Transaction.get*()` 
rename `QueryBuilder.requestCost*()` to `QueryBuilder.getCost*()`
add appropriate deprecation messages for existing APIs
closes #255
> unify idempotent method naming

- src/main/java/com/hedera/hashgraph/sdk/HederaCall.java
- src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
When reviewing, it was surprising that timeout came after the async callback parameters.
---
After we decide on the change, can you help me identify what functions need a deprecated equivalent.
> Move optional timeout to before the callback parameters

- pom.xml
@mehcode I think `proto.*` just excludes subpackages but `proto` will exclude that package and all subpackages: https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#excludePackageNames
closes #287
> fix javadoc package exclusion

- examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/MultiAppTransfer.java
- examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/TransferCrypto.java
- src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractCreateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractUpdateTransaction.java
This makes it harder to confuse with `ContractCreateTransaction.setContractMemo()` and `ConsensusTopicCreateTransaction.setTopicMemo()`.
> rename `Transaction.setMemo()` to `setTransactionMemo()`

- src/main/java/com/hedera/hashgraph/sdk/account/AccountCreateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractCreateTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/file/FileCreateTransaction.java
Since shards and realms are not yet implemented on the network, these methods won't function as expected.
Additionally, we never implemented `setShardId()` or `setRealmId()` for `FileCreate` because we didn't know the expected semantics of the nested `ShardID` and `RealmID` objects (if their fields were supposed to be mutually exclusive or what).
> deprecate shard/realm/adminKey setters for Create txns

- src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java
- src/main/java/com/hedera/hashgraph/sdk/Transfer.java
* deprecated `getTransfers()` in favor of field `transfers`
* (breaking-beta) renamed `memo` to `transactionMemo`
> TransactionRecord API changes

- src/main/java/com/hedera/hashgraph/sdk/file/FileInfoQuery.java
This is so it returns `FILE_DELETED` instead of `INSUFFICIENT_TX_FEE` for deleted files, where we get back a `COST_ANSWER` of 0.
closes #320
> set minimum cost for `FileInfoQuery`

- examples/src/main/java/com/hedera/hashgraph/sdk/examples/advanced/DeleteAccount.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountDeleteTransaction.java
- src/main/java/com/hedera/hashgraph/sdk/account/AccountInfoQuery.java
- src/main/java/com/hedera/hashgraph/sdk/contract/ContractInfoQuery.java
* `AccountInfoQuery` and `ContractInfoQuery` return a zero COST_ANSWER for deleted entities but the network won't accept a zero payment
* `AccountDeleteTransaction` requires the account ID in the transaction ID to be the same as the one being deleted
> cover some network idiosyncrasies

- pom.xml
updates the bintray url in `pom.xml` to `https` from `http`
fixes issue #328
> changes bintray url from http to https

- .editorconfig
- .github/workflows/java.yml
- .github/workflows/javadoc.yml
- android-example/app/build.gradle
- android-example/build.gradle
Also added a step to the Java workflow that runs `mvn install` on the SDK (which runs tests) before building `android-example`.
> fix Android example

- examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSubWithSubmitKey.java
- examples/src/main/java/com/hedera/hashgraph/sdk/examples/TopicWithAdminKey.java
I added 2 HCS-related examples:
- 1 publishing and subscribing to messages with a simple submitKey required for submit/publish
- 1 creating a new topic with a 2-of-3 threshold key, then updating that topic to a 3-of-4 threshold key
Removed the base class per @abonander comments on the previous PR and I can make it all 1 function like some of the other examples if that's desired.
There's no rush to get this on the hcs branch, and can just be merged to master when hcs is merged to master if that's easier.
> 2 HCS-related examples using submit and admin keys.

- examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSub.java
- examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSubWithSubmitKey.java
- examples/src/main/java/com/hedera/hashgraph/sdk/examples/TopicWithAdminKey.java
- Update HCS examples to use MirrorClient as opposed to ConsensusClient
- Have HAPI client pointing at Client.forTestnet() now that HCS is in testnet
- Don't hardcode fees
Fixes #340
> Update HCS examples to use MirrorClient and default to testnet

- src/main/java/com/hedera/hashgraph/sdk/HederaPrecheckStatusException.java
- src/main/java/com/hedera/hashgraph/sdk/HederaReceiptStatusException.java
- src/main/java/com/hedera/hashgraph/sdk/HederaRecordStatusException.java
- src/main/java/com/hedera/hashgraph/sdk/HederaStatusException.java
- src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/Status.java
- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- src/main/java/com/hedera/hashgraph/sdk/TransactionBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/TransactionId.java
These include additional context where available.
This solves the problem that `getRecord()` throws on the `getReceipt()` internal call even though records may contain useful information in the error case; in this case only `Busy` and `Unknown` are bubbled up and other status codes are ignored. If the transaction failed, the specific subclass of `HederaStatusException` will be `HederaRecordStatusException` which contains the record we fetched.
TODO:
> Add new exception types for different sources of status errors

- .github/workflows/java.yml
- pom.xml
- src/main/java/com/hedera/hashgraph/sdk/HederaPrecheckStatusException.java
- src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java
- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- src/test/java/com/hedera/hashgraph/sdk/integration_tests/ExceptionsTest.java
- src/test/java/com/hedera/hashgraph/sdk/integration_tests/TestEnv.java
Actually running these tests on CI is blocked on getting a testnet account and private key for CI.
> start integration testing by covering new exception types

- src/main/java/com/hedera/hashgraph/sdk/Status.java
- src/test/java/com/hedera/hashgraph/sdk/StatusTest.java
This ensures we have all possible response codes covered as long as we keep the protobufs up to date.
> test `Status.valueOf()` for all valid cases of `ResponseCodeEnum`

- pom.xml
- src/main/java/com/hedera/hashgraph/sdk/crypto/BadKeyException.java
- src/main/java/com/hedera/hashgraph/sdk/crypto/CryptoUtils.java
- src/main/java/com/hedera/hashgraph/sdk/crypto/Keystore.java
- src/main/java/com/hedera/hashgraph/sdk/crypto/PemUtils.java
- src/main/java/com/hedera/hashgraph/sdk/crypto/PrivateKey.java
- src/main/java/com/hedera/hashgraph/sdk/crypto/ed25519/Ed25519PrivateKey.java
- src/test/java/com/hedera/hashgraph/sdk/crypto/ed25519/Ed25519PrivateKeyTest.java
Tested working with an encrypted private key from OpenSSL
Deprecated `Ed25519PrivateKey.writePem()` for removal as the utility of the method is limited.
> implement encrypted PEM private key import

- src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- src/test/java/com/hedera/hashgraph/sdk/TransactionTest.java
If a duplicate signature is detected, simply return from the method call
Update tests to allow for duplicate signatures.
Closes #412
> Do not throw on duplicate signatures

- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
This PR resolves #459 
These changes are entirely semantic and replace `Retry` with `Attempt`, since this more closely captures the intent of this code. We are keeping track of the limit/count of retries, rather than a reference to any specific retry.
> Rename Executable retry limit field, getter and setter

- sdk/build.gradle
- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
Summary:
- Add a retry log for non-gRPC errors
- Change retry log level to warning
- Fix build failing due to depending on unstable master branch of jabel plugin
- Fix using verbose multi-line logs and printing a stacktrace
Details:
When the SDK is retrying a failed transaction, there is no logging by default to indicate there is an issue. With the default maxAttempts, that could mean up to almost a minute (~48s) could go by without any feedback to the user that something is wrong. They could increase the log levels to trace, but then the logs would become too verbose with request and response objects being printed.
It looks like the logs used to print at error level until very recently, most likely because they were too verbose due to using both a multi-line format and including a …
> Show warning during transaction retries

- sdk/src/main/java/com/hedera/hashgraph/sdk/Node.java
increaseDelay() was written in such a way that the minimum delay of 250 would never occur, because the delay integer would be doubled before the delay was actually carried out, so the minimum delay in practice was 500 instead of 250.
> Reordered the operations in Node::increaseDelay()

- sdk/src/main/java/com/hedera/hashgraph/sdk/TopicMessageQuery.java
Fixes #502 
This class has zero unit tests and I don't have the bandwidth to add that test coverage at this time. It would be nice if the SDK team could look into adding some in the future. You can do something [similar](https://github.com/hashgraph/hedera-mirror-node/blob/8dbb54f733af3ff0e7baff2ea37a5614124b5c27/hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/subscribe/grpc/GrpcClientSDKTest.java#L78) to what we do in the mirror node by using a stub for the mirror node gRPC API.
I would also recommend you allow the mirror node's grpc channel to support the [in-process channel builder](https://grpc.github.io/grpc-java/javadoc/io/grpc/inprocess/InProcessChannelBuilder.html) to reduce brittle timeout issues that can occur when using a real grpc channel in constrained CI …
> Various TopicMessageQuery fixes

- sdk/src/integrationTest/java/FeeSchedulesTest.java
Now `FeeSchedulesTest` actually tests whether file `0.0.111` actually appears to contain anything when deserialized.
> test: improved `FeeSchedulesTest`

- sdk/src/main/java/com/hedera/hashgraph/sdk/RequestType.java
`RequestType.UNCHECKED_SUBMIT` was missing from `RequestType::toString()` and `RequestType::valueOf()`
> fix: UNCHECKED_SUBMIT in RequestType

- sdk/src/integrationTest/java/ClientIntegrationTest.java
- sdk/src/integrationTest/java/FeeSchedulesTest.java
- sdk/src/integrationTest/java/ScheduleCreateIntegrationTest.java
- sdk/src/integrationTest/java/TransactionIntegrationTest.java
`testEnv` was not always closed after each integration test.  This needs to be done, or else scary-looking (but harmless) errors will clog up the screen while running integration tests.
> fix: testEnv must always be closed in integration tests.

- .github/workflows/testnet.yml
Attempt to fix CI when run from a fork. Current it fails since the secrets cannot be accessed from a forks pull request.
> fix: pull requests should run on forks using this repos secrets

- sdk/build.gradle
- sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Status.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/TopicMessageQuery.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/TopicMessageQueryTest.java
- Add a `TopicMessageQueryTest` for increased code coverage
- Change `TopicMessageQuery` reset stream regex to be more permissive and match the other SDKs
- Change `ManagedNode` to allow for in-process channels to make testing easier and more reliable
- Fix some javadoc errors in `Status` class
**Checklist**
> Add a TopicMessageQueryTest

- sdk/src/main/java/com/hedera/hashgraph/sdk/AccountBalance.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Hbar.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/PrivateKey.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/PublicKey.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/Ed25519PrivateKeyTest.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/Ed25519PublicKeyTest.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/HbarTest.java
- Add `toString()` to `AccountBalance`
- Make `Hbar.fromString()` understand unit symbol prefixes.
- Add `toStringRaw()` and `toStringDER()` to `PrivateKey` and `PublicKey`
- Add tests for these additions.
Fixes #561
> chore: add some string-conversion stuff

- CHANGELOG.md
- executable-annotation/src/main/java/com/hedera/hashgraph/sdk/FunctionalExecutable.java
- executable-processor/src/main/java/com/hedera/hashgraph/sdk/FunctionalExecutableProcessor.java
- sdk/src/integrationTest/java/ClientIntegrationTest.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Node.java
Closes: #478
`Client.getRequestTimeout()` is required to be exposed for `FunctionalExecutable` to work since it doesn't require `client` to be passed in as a parameter.
**Checklist**
> feat: implement `Client.ping[All]Async()`

- sdk/src/main/java/com/hedera/hashgraph/sdk/TokenNftTransfer.java
`TransferTransaction.getTokenNftTransfers()` is a public method but the `TokenNftTransfer` class it returns is not public. It should also be public so this method can be utilized by clients. Also, the other transfer getters return all public information so it should have parity with those.
**Checklist**
> Make TokenNftTransfer public

- CHANGELOG.md
- examples/src/main/java/CreateStatefulContractExample.java
- examples/src/main/java/UpdateAccountPublicKeyExample.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ChunkedTransaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ContractCreateTransaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/FileAppendTransaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/FileCreateTransaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Query.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleCreateTransaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleDeleteTransaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleSignTransaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/TokenAssociateTransaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/TokenCreateTransaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/TokenDissociateTransaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/TransferTransaction.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/ClientTest.java
Deprecates `Client.setMax[TransactionFee|QueryPayment]()`
Adds `Client.setDefaultMax[TransactionFee|QueryPayment]()` and `Client.getDefaultMax[TransactionFee|QueryPayment]()`
Fixes #612
**Checklist**
> fix: fix Client.max[TransactionFee|QueryPayment]

- CHANGELOG.md
- sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/ClientTest.java
- Add `minBackoff` option to `Client` with a default of 250ms
- Add `minBackoff` option to `Executable`
- Add `maxBackoff` option to `Client` with a default of 8s
- Add `maxBackoff` option to `Executable`
- Add validation that `maxAttempts` is greater than zero
- Fix `Executable` logs not showing concrete class name
Fixes #614 
**Checklist**
> Add minBackoff and maxBackoff to Client and Executable

- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/TopicMessageQuery.java
`Executable` now retries on `RST_STREAM`.
This PR does not include tests for this feature.  Those will be in a separate PR.
Fixes #611
**Checklist**
> fix: retry on RST_STREAM

- CHANGELOG.md
- sdk/src/main/java/com/hedera/hashgraph/sdk/NftId.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/NftIdTest.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/NftIdTest.snap
`NftId.[to|from]string()` now uses format `1.2.3/4` instead of `1.2.3@4`
**Checklist**
> Chore: change NftId.toString() format

- CHANGELOG.md
- sdk/src/main/java/com/hedera/hashgraph/sdk/TransferTransaction.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/CryptoTransferTransactionTest.java
Bring `TransferTransaction.getTokenIdDecimals()` in line with [the SDK reference](https://github.com/hashgraph/hedera-sdk/blob/main/reference/cryptocurrency/TransferTransaction.md#gettokeniddecimals-map--tokenid-uint32-)
**Checklist**
> Fix: bring getTokenIdDecimals() in line with reference

- sdk/src/integrationTest/java/AccountBalanceIntegrationTest.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ExecutionState.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceiptQuery.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecordQuery.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/ExecutableTest.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/HederaTrustManagerTest.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/TokenPauseTransactionTest.java
Signed-off-by: Albert Tam <albert.tam@hedera.com>
Change the retry scheme to move onto the next healthy node without delay. If all the nodes are deemed unhealthy then select the node with the shortest delay remaining. Also remove the delay whenever an error is encountered, choosing to retry the request with another node immediately.
Fixes #803
Had to make GrpcRequest package protected to enable it to be unit-tested.
No change made to the API so no impact to user experience, internal improvement only.
**Checklist**
> Minimize delays when picking node for request (#803)

- sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/TransactionRecordTest.java
The encoding in TransactionRecord.toProtobuf misses encoding the NFT transfers.
**Checklist**
> TransactionRecord.toProtobuf misses NFT transfers

- sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ManagedNodeAddress.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNode.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/ManagedNodeAddressTest.java
* Fix incorrect port used for TLS detection
* Fix use of hard coded `overrideAuthority("127.0.0.1")` which doesn't work with the CA signed certificates the mirror node uses
Fix #855
**Checklist**
> Fix TLS issues with mirror node

- CHANGELOG.md
- scripts/.gitignore
- scripts/generate_contract_function_param_methods.py
- scripts/update_protobufs.py
- sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionParameters.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/ContractFunctionParametersTest.java
Add script to auto-generate `ContractFunctionParameters.add[Int|Uint]N()` and `.add[Int|Uint]NArray()` methods, and add the generated methods to the class.
Fixes #901
**Checklist**
> Feat: Function param widths

- CHANGELOG.md
- sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionResult.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ContractStateChange.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/StorageChange.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/ContractInfoTest.snap
Signed-off-by: Daniel Akhterov <akhterovd@gmail.com>
Fixes #
**Checklist**
> fix: deprecate `ContractFunctionResult.stateChanges`

- CHANGELOG.md
- sdk/src/main/java/com/hedera/hashgraph/sdk/ContractId.java
https://github.com/hashgraph/hedera-sdk-js/issues/1188
**Checklist**
> fix: undeprecate `*ContractId.fromSolidityAddress()`

- sdk/src/main/java/com/hedera/hashgraph/sdk/TopicMessageQuery.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/TopicMessageQueryTest.java
* Remove logging when unsubscribing from TopicMessageQuery
Fixes #1174
> fix: remove logging when unsubscribing from TopicMessageQuery

- CHANGELOG.md
- sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/ClientCloseTest.java
This PR reverts some changes from #1091 in order to fix block when running tests in CI
Fixes #1175
**Checklist**
> Fix: execute can ignore timeout and block indefinitely 

- CHANGELOG.md
- examples/src/main/java/ExemptCustomFeesExample.java
This PR proves that the HIP-573 is working properly.
Fixes #1169
> test: Add HIP-573 example

- .github/workflows/build.yml
- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
Only evaluate the logger parameter in Executable listeners if trace logs are enabled
Fixes #1181 
**Checklist**
> Fix: Executable listeners generate lots of logs even if trace is not enabled

- CHANGELOG.md
- sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/ExecutableTest.java
* `Executable.execute(Client client, Duration timeout)` now sets gRPC deadline to the underlying gRPC request
* new executableShouldUseGrpcDeadline() added to ExecutableTest.java
* **Related issue(s)**:
Fixes #1226 
**Checklist**
> Fix: Executable.execute to set gRPC deadline #1226

- CHANGELOG.md
- sdk/src/main/java/com/hedera/hashgraph/sdk/TokenNftInfo.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/TokenNftInfoTest.snap
Renames allowanceSpenderAccountId to spenderId in TokenNftInfo to follow the protobuf specification.
Fixes #1254 
**Checklist**
> fix: rename allowanceSpenderAccountId to spenderId in TokenNftInfo

- CHANGELOG.md
- sdk/src/main/java/com/hedera/hashgraph/sdk/Mnemonic.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/MnemonicTest.java
This PR modifies Mnemonic seed generation when a passphrase is used. In order to support BIP-39 the passphrase is normalized to NFKD.
Fixes #1240 
Should we normalize the whole mnemonic and not just the passphrase?
**Checklist**
> BIP39 - mnemonic passphrase normalize to NFKD

- sdk/protobuf-lite.gradle
Bump protobuf-javalite from 3.21.1 to 3.21.9 to fix https://nvd.nist.gov/vuln/detail/CVE-2022-3171
**Checklist**
> Bump protobuf-javalite to 3.21.9

- sdk/src/main/java/com/hedera/hashgraph/sdk/TopicMessageQuery.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/TopicMessageQueryTest.java
This PR modifies the onError logic in TopicMessageQuery to properly handle and log Cancelled status codes.
Fixes #1278 
I couldn't find a clean solution to unit test the actual Logger Warn Message, currently the logger is a static field and it's not easy to mock it (LoggerFactory as well).
**Checklist**
> Fix error handling and logging in TopicMessageQuery

- sdk/src/main/java/com/hedera/hashgraph/sdk/Mnemonic.java
…ked locking
Makes `Mnemonic.getSpecificWordList()` synchronized and removes the double-checked locking idiom
Fixes #1334 
**Checklist**
> fix: Replace double-checked locking in getSpecificWordList()

- CHANGELOG.md
- examples/src/main/java/AccountAliasExample.java
- examples/src/main/java/AutoCreateAccountTransferTransactionExample.java
Removes references for lazy account creation and renames `LazyCreateTransferTransactionExample` to `AutoCreateAccountTransferTransactionExample`
Fixes #1339 
**Checklist**
> Chore: remove references for lazy account creation

- CHANGELOG.md
- sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNetwork.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNode.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNodeAddress.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNode.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Network.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Node.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/BaseNodeAddressTest.java
Changes:
- `setTransportSecurity()` and `getNodesForKey()` moved from `BaseNetwork` to `Network`
- `toInsecure()` and `toSecure()` moved from `BaseNode` to `Node`
- Removed `PORT_MIRROR_PLAIN` from `BaseNodeAddress`
Fixes #1316 
**Checklist**
> Fix: remove the insecure port of mirror nodes

- sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNetwork.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/LockableList.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/ExecutableTest.java
This PR modifies the node retry logic in order to support all node proxies on a single node account id.
Fixes #796 
**Checklist**
> Node retry logic - retry all node proxies if a single node is specified

- sdk/src/integrationTest/java/IntegrationTestEnv.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNode.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/ExecutableTest.java
Fix for issue timeout for `TransactionResponse.getReceipt` not working well. 
Fixes #1497
**Checklist**
> Fixing timeout for `TransactionResponse#getReceipt` not working well

- examples/build.gradle
Fix for `java.lang.VerifyError` exception in examples.
Fixes #1478 
**Checklist**
> Fix for `java.lang.VerifyError` exception in examples.

- sdk/src/integrationTest/java/AccountIdPopulationIntegrationTest.java
- sdk/src/integrationTest/java/ContractIdPopulationIntegrationTest.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/AccountId.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ContractId.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/EntityIdHelper.java
- added checks inside `fromSolidityAddress()` and, based on the result, pass the flow to the proper method ([Reference PR](https://github.com/hashgraph/hedera-sdk-js/pull/1741/files));
- added `populateAccountNum()` to `AccountId` and `ContractId` classes ([Reference PR](https://github.com/hashgraph/hedera-sdk-go/pull/784/files)).
Fixes #1537 
**Checklist**
> Add `populateAccountNum()` to `AccountId` and `ContractId` classes

- CHANGELOG.md
- README.md
- example-android/app/build.gradle
- version.gradle
Stable release 2.28.0
Fixes #
**Checklist**
> Prepare for stable release 2.28.0

- sdk/src/test/java/com/hedera/hashgraph/sdk/SystemDeleteTransactionTest.java
- added more unit tests for `SystemDeleteTransaction`;
- reformatted and rearranged code;
Fixes #1576 
Please pay attention to `resetFileId` and `resetContractId` tests -- setter functions in the Java SDK work differently then in C++ SDK, hence, these tests do not pass.
**Checklist**
> Add more unit tests for `SystemDeleteTransaction`

- sdk/src/integrationTest/java/AccountIdPopulationIntegrationTest.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/AccountId.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/EntityIdHelper.java
Fix `AccountId#toSolidityAddress()` does not return expected result when AccountId has a Key Alias
Fixes #1586 
**Checklist**
> Fix `AccountId#toSolidityAddress()` does not return expected result when AccountId has a Key Alias

- sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionId.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/DuplicateTransactionTest.java
Fix generated transaction IDs are not unique issue.
Fixes #1557 
**Checklist**
> Fix generated transaction IDs are not unique issue.

- sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionId.java
Small updates, based on the review of #1587.
Fixes #1557
> Fix generated transaction IDs are not unique issue small updates

- sdk/src/main/java/com/hedera/hashgraph/sdk/AccountInfo.java
Hotfix issue #1571.
Fixes #1571
> Hotfix issue #1571.

- sdk/src/main/java/com/hedera/hashgraph/sdk/Delayer.java
Hotfix issue #1606. Prevents Android app on API level 30 from crashing.
Fixes #1606
> Hotfix issue #1606.

- .github/workflows/build.yml
Downgrade `hedera-local-node` version to fix failing PR check (Build / test (pull_request)).
Fixes #1625
> Fix failing PR check (Build / test (pull_request))

- .github/workflows/release-artifacts.yml
- build.gradle
- sdk/build.gradle
This pull request changes the following:
- Adds a new CI pipeline which will publish and release the SDK artifact via Maven Central.
- This workflow will ensure the Gradle project version matches the semantic version tag.
- Closes #1664
> chore: add CI pipeline to release SDK artifacts to Maven Central

- sdk/src/integrationTest/java/EthereumTransactionIntegrationTest.java
This PR temporarily disables the HIP-844 integration test -- `EthereumTransactionIntegrationTest#signerNonceChangedOnEthereumTransaction()`
> test: disable HIP-844 integration test

- .github/workflows/release-artifacts.yml
- sdk/build.gradle
- sdk/src/test/java/com/hedera/hashgraph/sdk/ContractInfoTest.snap
- sdk/src/test/java/com/hedera/hashgraph/sdk/ContractNonceInfoTest.snap
This PR ports the previous workaround for releasing the `sdk-full` artifact as a temporary solution until #1732 is merged.
Fixes #
**Checklist**
> chore: apply workaround for sdk-full release

- sdk/src/main/java/com/hedera/hashgraph/sdk/AccountBalance.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/AccountInfo.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ContractInfo.java
This PR undeprecates fields that are populated from the Mirror Node REST API.
Closes #1820
> chore: undeprecate fields that are populated from the Mirror Node REST API

- sdk/src/main/java/com/hedera/hashgraph/sdk/AccountId.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ContractId.java
This PR deprecates `populateAccountNumAsync`, `populateAccountEvmAddressAsync` methods in `AccountId` and `populateContractNumAsync` in `ContractId`.
Closes #1823
> chore: deprecate populateAccountNumAsync, populateAccountEvmAddressAsync methods in AccountId and populateContractNumAsync in ContractId

- scripts/update_protobufs.py
- sdk/src/main/java/com/hedera/hashgraph/sdk/RequestType.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Status.java
- sdk/src/main/proto/address_book_service.proto
- sdk/src/main/proto/basic_types.proto
- sdk/src/main/proto/crypto_create.proto
- sdk/src/main/proto/crypto_update.proto
- sdk/src/main/proto/node.proto
- sdk/src/main/proto/node_create.proto
- sdk/src/main/proto/node_delete.proto
- sdk/src/main/proto/node_get_info.proto
- sdk/src/main/proto/node_update.proto
- sdk/src/main/proto/query.proto
- sdk/src/main/proto/response.proto
- sdk/src/main/proto/response_code.proto
- sdk/src/main/proto/schedulable_transaction_body.proto
- sdk/src/main/proto/transaction_body.proto
- sdk/src/main/proto/transaction_receipt.proto
This PR addresses the issue when gradle build fails with an error after updating protobufs.
Following step was automated in relevant python script: updating protobuf imports in the processed protobufs under `sdk/src/main/proto` (removing `state/` in order to import protobufs from the same folder).
Also protobufs were updated to validate fix against CI checks.
Closes #1747
> fix: build fail after updating protobufs

- gradle/plugins/src/main/kotlin/com.hedera.gradle.root.gradle.kts
...by applying 'com.hedera.gradle.base' to root.
This is needed by the Nexus publishing mechanism.
**Checklist**
> fix: set 'group' in root project

- Taskfile.yml
- scripts/update_protobufs.py
This PR update the `update:proto` task and corresponding python script to pull protobufs from latest released tag by default with optional override in the form of `task update:proto  proto=[branch]` or `task update:proto  proto=[tag]`
* update taskfile
* update python script
Fixes #1908
**Checklist**
> chore: pull protobufs from latest tag

- sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceipt.java
- sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/FileUpdateIntegrationTest.java
handle `FEE_SCHEDULE_FILE_PART_UPLOADED` status in transaction receipt
Fixes https://github.com/hashgraph/hedera-sdk-java/issues/1950
**Checklist**
> fix: handle `FEE_SCHEDULE_FILE_PART_UPLOADED` status

- .github/workflows/build.yml
- .github/workflows/disabled/main.yml
- .github/workflows/disabled/previewnet.yml
- .github/workflows/disabled/testnet.yml
- .github/workflows/pages.yml
- .github/workflows/release-artifacts.yml
This pull request changes the following:
- Updates the CI workflows `runs-on` labels to use the new Latitude.sh based runners.
- Closes #1973
> ci: update workflows to use latitude.sh based runners

- sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionParameters.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionResult.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/EntityIdHelper.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/EthereumFlow.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Query.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/TokenRejectFlow.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java
The Java SDK is currently built using Java 17 and utilizes features and APIs up to Java 17. Therefore, it should be used by applications built with Java 17 or higher. However, Java 17 is only supported by the latest Android API (API level 34). 
Officially, Hedera claims that the Java SDK should be compatible with Android API level 26 and above.
The root cause of the issue is that when an Android application encounters a Java API call (such as `getModule`, `toList`, etc.) that it does not support—either due to an unsupported API level or other reasons like not supporting Java module system—it crashes at runtime. This issue is not detectable during compile time.
This PR removes usages of not supported functions where possible and adds docs to notify users for the specific …
> fix: Android `toList` runtime issue

- sdk/src/main/java/com/hedera/hashgraph/sdk/SystemDeleteTransaction.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/SystemDeleteTransactionTest.java
The setter methods setFileId and setContractId in SystemDeleteTransaction.java are not behaving as expected. This pr uses proposed solution
- code is working
- disable annotation and related comments removed from tests
- tests passes
Fixes #1596
**Checklist**
> fix:reset setFileId and setContractId #1596

- sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java
- sdk/src/testIntegration/java/com/hedera/hashgraph/sdk/test/integration/ClientIntegrationTest.java
This PR ignores a node when the node is not present in the address book, instead of throwing an exception.
This helps with wallets not having to update the SDK every time the address book gets changed.
Fixes #2044
**Checklist**
> chore: remove `IllegalStateException` when specific node id is not present in address book

- sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
The `Client`-Class gained some considerable size over time. I refactored the `Client`-Class a bit to make the `Client.fromConfig()`-construction logic more clear and to shrink the Client Class, by extracting the logic to the inner `Config` class.
Downside: `Client` and `Config` now have a bidirectional relationship, making this a little harder to understand. But the Config class is private to the Client class, so this added complexity does not leak outside. 
Looking forward to your opinions regarding this refactorings.
This PR modifies ... in order to support ...
* extract `Client.fromConfig`-Construction logic to `Config` class
* extracted more methods to make the code more readable
Fixes #
**Checklist**
> refactor: Extract fromConfig() logic from Client

- tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/TokenService.java
- tck/src/main/java/com/hedera/hashgraph/tck/methods/sdk/param/TokenDeleteParams.java
Implement `tokenDelete` for TCK
Fixes #2089
**Checklist**
> feat(TCK): Implement `tokenDelete`

- sdk/src/main/java/com/hedera/hashgraph/sdk/NodeCreateTransaction.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/NodeUpdateTransaction.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/NodeCreateTransactionTest.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/NodeUpdateTransactionTest.java
This PR fixes:
1. `NodeCreate` and NodeUpdate have nullable fields that cannot be set to null.
2. `NodeUpdateTransaction` gossip and grpc certificate bytes deserialize to empty `ByteValue`/`ByteString`
Fixes #2090 #2091
**Checklist**
> chore: fix serialize/deserialize for `NodeUpdate` and `NodeCreate`

- sdk/src/main/java/com/hedera/hashgraph/sdk/NodeUpdateTransaction.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/NodeUpdateTransactionTest.java
> fix: `NodeUpdateTransaction` sets description as empty string

- sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNode.java
- sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionId.java
- Replaces `getModule()` and `Random` , because it's not compatible with Android API 26
Fixes #2095
**Checklist**
> fix(Android): Executing transaction fails at runtime

- sdk/src/main/java/com/hedera/hashgraph/sdk/Endpoint.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/NodeCreateTransactionTest.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/NodeUpdateTransactionTest.java
This PR fixes `Endpoint` overriding the port if it is 0 or 50111
Fixes #2098
**Checklist**
> fix: Do not override service port

- hiero-dependency-versions/build.gradle.kts
- sdk-full/build.gradle.kts
- sdk/build.gradle.kts
Some versions for _dependency groups_ – such as all `io.grpc:*` dependencies – were defined multiple times. This let to multiple Dependabot PRs for the same versions, leading to inconsistencies between merging of the several PRs.
Each repeated version is now only defined once in a `val` in the `hiero-dependency-versions/build.gradle.kts` file. This notation is supported by Dependabot.
This also addresses the point **Resolve duplication in constraints publishing (right now there is some duplication)** of issue #1794.
#1794
**Checklist**
> build: remove duplicated dependency versions

- .github/workflows/build.yml
- .github/workflows/disabled/testnet.yml
- gradle/aggregation/build.gradle.kts
This now follows a similar setup as in hedera-services. This update was missed in #2033.
> build: repair running test AND testIntegration with code coverage on CI

- settings.gradle.kts
Updates the gradle conventions plugins to v0.1.4 to fix publishing to MC
**Related Issue(s)**:
Fixes #2151
> chore: Update gradle build plugins version to 0.1.4

- .github/CODEOWNERS
- .github/workflows/build.yml
- .github/workflows/disabled/main.yml
- .github/workflows/disabled/previewnet.yml
- .github/workflows/disabled/testnet.yml
- .github/workflows/pages.yml
- .github/workflows/release-artifacts.yml
Update codeowners and runs-on stanzas
**Related Issue(s)**:
Fixes #2191
> ci: Update self-hosted-runners for hiero-ledger transfer

- .github/CODEOWNERS
Description:
As defined in Hiero (https://github.com/hiero-ledger/governance?tab=readme-ov-file#definitions-of-roles) all committers should have write access which includes acting as a code owner for the repo.
Closes #2225
> chore: fix committers group access

- .github/workflows/release-artifacts.yml
This action was set to the crazy-max version while the step-security org license was getting sorted out. Now we can revert it back.
Fixes #2290 
**Checklist**
> chore: switch import gpg key action to step-security maintained version

- examples/README.md
- examples/src/main/java/com/hedera/hashgraph/sdk/examples/SpecificNodeExample.java
This PR adds a new example that demonstrates three different approaches to communicate with specific nodes in the Hedera network:
1. Direct node specification - Creating a custom network map with only specific nodes
2. Extracting from network map - Getting the full network and then extracting specific nodes
3. Using TLS with specific nodes - Demonstrating secure communication with specific nodes
The example includes detailed documentation comments explaining each approach and when to use them.
Fixes #1594
> Add example demonstrating how to communicate with specific nodes

- sdk/build.gradle.kts
- sdk/src/main/java/module-info.java
- settings.gradle.kts
Update _hiero-gradle-conventions_ to _0.4.0_ and by that run tests on the _module path_.
See https://github.com/hiero-ledger/hiero-consensus-node/pull/18922 for more details on how that works.
> build: run tests on module path

- hiero-dependency-versions/build.gradle.kts
- sdk/src/main/java/com/hedera/hashgraph/sdk/EthereumFlow.java
Possible scenario:
AccountCreateTransaction is sent to node 1 - SUCCESS
FileCreateTransaction is sent to node 2 - SUCCESS
FileAppendTransaction is sent to node 3 - PAYER_ACCOUNT_NOT_FOUND
The last two transactions are part of EthereumFlow execution, where user has no control over which node[s] to use.
Fixes https://github.com/hiero-ledger/hiero-sdk-java/issues/2358
**Checklist**
> Single node usage for the whole EthereumFlow

- settings.gradle.kts
Update hiero-gradle-conventions to v0.4.5 to fix issue with OSSRH URL in Maven Central.
**Related Issue(s)**:
Fixes #2394
> chore: update hiero-gradle-conventions to v0.4.5

- sdk/src/main/java/com/hedera/hashgraph/sdk/TopicMessageQuery.java
- sdk/src/test/java/com/hedera/hashgraph/sdk/TopicMessageQueryTest.java
Disable retries when customer unsubscribes from a topic.
**Related issue(s):**
Fixes https://github.com/hiero-ledger/hiero-sdk-java/issues/2453
**Checklist**
> fix: reties on topic unsubscribe
